### ISSUE TITLE
Anki syncing / repo

### ISSUE THREAD

**Issue by RvNovae** [importPI19fromDHGE/dhge-pi19-sem4#115]
Entweder für git:
https://ankiweb.net/shared/info/1788670778

Oder jemand setzt einen sync server auf:
https://github.com/ankicommunity/anki-sync-server

Weil Anki ist schon ein gutes tool zum lernen.

**Comment by Steve2955** [comment]
@RvNovae Ich dachte der sync-server ist nur dazu da, um Fortschritte zu synchronisieren?

**Comment by Steve2955** [comment]
Ziel in Sem5 sollte es sein eine [md2anki](https://github.com/JoshuaGross/md2anki) Action laufen zu lassen. Das genau Tool kann man sich nochmal raussuchen

**Comment by RvNovae** [comment]
Das klingt auch cool. Bin mal gespannt, wie gut das funktioniert.

**Comment by Steve2955** [comment]
Wenn man so ne Action laufen hat, braucht man sich vielleicht auch nicht um die Versionierung der `.apkg`s sorgen, sondern kann die Files einfach in ein Release reinpacken (analog zu den PDFs) oder irgendwas mit `git lfs` anstellen?

**Comment by RvNovae** [comment]
Die Versionierung der `apkg`s wird ja über die Versionierung der Markdown Dokumente realisiert.

**Comment by nukerxy** [comment]
> Die Versionierung der `apkg`s wird ja über die Versionierung der Markdown Dokumente realisiert.
> 
> Und ja, würde die dann auch bei den Release PDFs mit reinpacken.

Ich kann mir vorstellen, dass es zu Problemen kommen kann - müssen wir ausprobieren, aber nicht überrascht sein.

Angenommen man importiert individuell immer wieder die überarbeitete Version des Decks
Dann sind Umbenennungen am Level 2 Header bestimmt = neue Karten
Entsprechend müsste man hin und wieder das lokale Deck aussortieren oder das lokales Deck inklusive Lernfortschritt löschen und das Git-Deck importieren.

**Comment by RvNovae** [comment]
Stimmt, daran hatte ich nicht gedacht.

**Comment by nukerxy** [comment]
Kurz um das hier abzulegen:
von https://www.quora.com/What-is-the-best-way-to-collaborate-on-Anki-decks
kam der Tipp zu https://ankiweb.net/shared/info/1672832404

> Useful when you need to edit with an external software (eg Excel) a large collections of cards. To ensure the edited cards merge properly when importing back into Anki, the unique card id is critical.

5 years ago, vielleicht schon Teil von Anki; muss weiter recherchieren

**Comment by nukerxy** [comment]
> Entweder für git:
> https://ankiweb.net/shared/info/1788670778

Das sieht sehr passend aus

**Comment by nukerxy** [comment]
Das hier habe ich noch ausgegraben
https://github.com/OnkelTem/anki-dm

**Comment by Steve2955** [comment]
@nukerxy @RvNovae Also ich würde mich hier wirklich auf Markdown zu Anki Umwandlungen konzentrieren. Dazu gibt's ja auch schon einige Tools, die im Internet rumliegen, aber so richtig zufrieden war ich eigentlich mit keinem. [Ich hab daher selbst mal ein bisschen rumgebastelt.](https://github.com/Steve2955/md2anki) Ist zwar erstmal nur ein Prototyp/MVP, aber ich denke man könnte das beliebig erweitern und an unsere Anforderungen anpassen. 
Von der Versionierung von JSON Repräsentationen von Decks würde ich persönlich Abstand nehmen wollen.

**Comment by nukerxy** [comment]
Das Ganze läuft in dhge-pi19-sem5 sehr gut.
