### ISSUE TITLE
Error producing PDF: Undefined control sequence.

### ISSUE THREAD

**Issue by Steve2955** [importPI19fromDHGE/dhge-pi19-sem4#34]
@ZeroPointMax @RvNovae Unser [PDF-build failed mal wieder](https://github.com/importPI19fromDHGE/dhge-pi19-sem4/runs/2500198292) 😅

Ich vermute da ist irgendwo ein Unicode-Zeichen drin oder so ähnlich, mit dem LaTeX nicht klar kommt. [Irgendwo in DBS Line 178++](https://github.com/importPI19fromDHGE/dhge-pi19-sem4/edit/main/DBS-DORENDORF/README.md), ich hab aber auf den ersten Blick nichts gesehen 🤔

**Comment by nukerxy** [comment]
Erstmal sorry, dass ich ihn nochmal gestartet habe, falls ihr ne Email bekommen habt :D

Z. 181 in readme
wird zu Latex  

>  \(\rightarrrow\) 

Das sieht nicht richtig aus?!
Zeile 1508 im Log

>  ! Undefined control sequence.
> l.909   \(\rightarrrow
>                       \) keine Anomalien

noch ohne Fehler
In Log Zeile 1717 dann das gleiche als letzte Meldung -  danach vor die Wand gefahren

**Comment by ZeroPointMax** [comment]
rrr ist der Fehler

**Comment by ZeroPointMax** [comment]
Sorry, aber wir haben einen [neuen Fehler](https://github.com/importPI19fromDHGE/dhge-pi19-sem4/runs/2501247663)

**Comment by ZeroPointMax** [comment]
Die letzten Zeilen sehen so aus:

```
[1] (/opt/texlive/texdir/texmf-dist/tex/latex/lm/omllmm.fd)
(/opt/texlive/texdir/texmf-dist/tex/latex/amsfonts/umsa.fd)
(/opt/texlive/texdir/texmf-dist/tex/latex/microtype/mt-msa.cfg)
(/opt/texlive/texdir/texmf-dist/tex/latex/amsfonts/umsb.fd)
(/opt/texlive/texdir/texmf-dist/tex/latex/microtype/mt-msb.cfg)
Underfull \hbox (badness 10000) in paragraph at lines 527--529
[]\TU/SourceSansPro(0)/b/n/10.95 asymmetrische Verschlüsselung: \TU/SourceSansP
ro(0)/m/n/10.95 privater und öffentlicher Schlüssel (meist für Ent-
[2] [3]
! Missing number, treated as zero.
<to be read again> 
                   (
l.640 \textbf
             {Vorteile} & \textbf{Nachteile} \\
Output written on /tmp/tex2pdf.-7f696d487d09cb50/input.pdf (3 pages).
Transcript written on /tmp/tex2pdf.-7f696d487d09cb50/input.log.

Error producing PDF.
! Missing number, treated as zero.
<to be read again> 
                   (
l.640 \textbf


```

**Comment by nukerxy** [comment]
Fehler tritt wohl in [Kasches Datei ](https://github.com/importPI19fromDHGE/dhge-pi19-sem4/blob/46227423299cbc5144bcbb55ea2e7179496bd77c/PRO-KASCHE/README.md) auf ?

> []\TU/SourceSansPro(0)/b/n/10.95 asymmetrische Verschlüsselung: \TU/SourceSansP
> ro(0)/m/n/10.95 privater und öffentlicher Schlüssel (meist für Ent-
> [2] [3]
> ! Missing number, treated as zero.
> <to be read again> 

--> In der Datei steht  

> **asymmetrische Verschlüsselung:** privater und öffentlicher Schlüssel (meist für Ent-/verschlüsseln)
> - z.B. End-to-End verschlüsselte Chat-Programme, PGP, Digitale Signaturen

Der Forward-Slash könnte das Problem sein.

**Comment by nukerxy** [comment]
zu [meinem Kommentar](https://github.com/importPI19fromDHGE/dhge-pi19-sem4/issues/34#issuecomment-832126082)

Andere Dateien mit Forward Slash laufen durch, z.b. ABWL Leder; ist die erste Datei heute gewesen.
Weitersuchen..

**Comment by nukerxy** [comment]
Mich wunder außerdem, dass 

> \textbf{Vorteile} & \textbf{Nachteile} \\

explizit erwähnt wird.
Latein am Ende.

**Comment by Steve2955** [comment]
```
Underfull \hbox (badness 10000) in paragraph at lines 527--529
[]\TU/SourceSansPro(0)/b/n/10.95 asymmetrische Verschlüsselung: \TU/SourceSansP
ro(0)/m/n/10.95 privater und öffentlicher Schlüssel (meist für Ent-
[2] [3]
! Missing number, treated as zero.
<to be read again> 
                   (
l.640 \textbf
             {Vorteile} & \textbf{Nachteile} \\
```

@nukerxy So wie ich das verstehe ist der Punkt mit *asymmetrische Verschlüsselung...* nur eine `Underfull \hbox`, kann man in der Regel ignorieren (würde ich zumindest als LaTeX-Noob behaupten 😅 )

Der tatsächliche Fehler liegt meines Erachtens nach bei der Tabelle mit den Vor- und Nachteilen 🤔 

````tex
\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.49}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.51}}@{}}
\toprule
\textbf{Vorteile} & \textbf{Nachteile} \\
\midrule
\endhead
- dezentral, unabhängig von Zentralbanken & - hohe Eigenverantwortung
der Nutzer (ohne Private-Key kein Zugriff auf Wallet) \\
- sicherer Wertspeicher (maximale Anzahl von BTC begrenzt) & -
irreversible Transaktionen (Diebstahl, \ldots) \\
- freie weltweite Transaktionen, ohne Sanktionen und hohe
Transaktionskosten & - legt alle Transaktionen offen (Nachverfolgbarkeit
vs.~Privatsphäre) \\
& - Nutzung für illegale Transaktionen möglich (Silk Road, \ldots) \\
& - hoher Stromverbrauch des verbreiteten Mining-Algorithmus \\
\bottomrule
\end{longtable}
```

**Comment by Steve2955** [comment]
Ohne Theme kann ich es übrigens lokal umwandeln, mit Theme läuft irgendetwas nicht, kommt aber eine andere Fehlermeldung:

```
! Undefined control sequence.
<argument> \AddToHook
                      {file/after/tracklang.sty}{\@ifpackagelater {tracklang...
l.26 }

No pages of output.
```

**Comment by nukerxy** [comment]
@photovoltex 
@RvNovae 
Ideen?

**Comment by photovoltex** [comment]
& ist ein Sonderzeichen welches meist in Tabellen verwendet wird... muss deshalb immer in default Latex escaped werden insofern keine Tabelle oder andere Enivorment in welcher dieses benutzt wird also könnte funktionieren
`\textbf{Vorteile} \& \textbf{Nachteile} \\`

**Comment by photovoltex** [comment]
nächster Versuch...

[kasche](https://github.com/importPI19fromDHGE/dhge-pi19-sem4/blame/main/PRO-KASCHE/README.md) line 59
`- **asymmetrische Verschlüsselung:** privater und öffentlicher Schlüssel (meist für Ent-/verschlüsseln)`
mich macht das forward slash etwas wirre da es im log exakt an der stelle abbricht
```
Underfull \hbox (badness 10000) in paragraph at lines 527--529
[]\TU/SourceSansPro(0)/b/n/10.95 asymmetrische Verschlüsselung: \TU/SourceSansP
ro(0)/m/n/10.95 privater und öffentlicher Schlüssel (meist für Ent-
[2] [3]
! Missing number, treated as zero.
<to be read again> 
                   (
l.640 \textbf
             {Vorteile} & \textbf{Nachteile} \\
Output written on /tmp/tex2pdf.-7f696d487d09cb50/input.pdf (3 pages).
```

Ich würde mal vermuten das es das forward slash nicht richtig interpretiert wird?

**Comment by photovoltex** [comment]
Okay es liegt genau an [PRO-KASCHE](https://github.com/importPI19fromDHGE/dhge-pi19-sem4/blame/main/PRO-KASCHE/README.md) line 59
sobald ich dort den Bindestrich entferne geht es `-/ `  ->  `/`

auch könnte evtl `(Ent)verschlüsseln` funktionieren... dabei gibt es zwar eine Warnung die sagt dass die "hbox" zu groß ist was (10pt) sein sollten aber das sollte kein Problem sein außer ihr mögt eure Ränder und das sie überall gleich sind mehr ^^

**Comment by Steve2955** [comment]
Hat leider nicht viel geändert, nur die `Underfull \hbox` ist weg 😅 

```
! Missing number, treated as zero.
<to be read again> 
                   (
l.640 \textbf
             {Vorteile} & \textbf{Nachteile} \\
Output written on /tmp/tex2pdf.-e23db55b793cfaec/input.pdf (3 pages).
Transcript written on /tmp/tex2pdf.-e23db55b793cfaec/input.log.

Error producing PDF.
! Missing number, treated as zero.
<to be read again> 
                   (
l.640 \textbf
```

**Comment by RvNovae** [comment]
Also ich sehe hier auf die schnelle auch nichts, wenn ich ehrlich bin.

**Comment by nukerxy** [comment]
> \item
  \textbf{asymmetrische Verschlüsselung:} privater und öffentlicher
  Schlüssel (meist für Ent-/verschlüsseln)

Ist es der Doppelpunkt?!?!?!

**Comment by nukerxy** [comment]
Neue Idee:

 \begin{longtable}[]{@{} 
 \> {\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.49}}
 \>{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.51}}@{}}
\toprule

Sind die spitzen Klammern gültige Syntax? Ich hab das mal in Overleaf durchlaufen lassen - Fehler in der hier zweiten Zeile.

**Comment by nukerxy** [comment]
Ich kriege 4x undefined --> 
nach den Meldungen: 2x Columnwidth und 1x raggedright 
und {0.51}@{} 

sowie 1x illegal charachter in array arg. ?!

"You're in trouble here." 😄
