### ISSUE TITLE
TOC Generator closes Pull-Requests 

### ISSUE THREAD

**Issue by nukerxy** [importPI19fromDHGE/dhge-pi19-sem4#59]
#55 #56 
#57 -> Yannis weiß Bescheid
#58 
Beobachtung:
PR wird geschlossen, Branch wird gelöscht.
Alle PR haben /SWE-KASCHE/appendix/LKF.md geändert.
Alle PR wollten Branch auf anderen Branch mergen, der **nicht** main ist.
Alle PR hatten Linting Errors (probably unrelated).

Recherche:
TOC-Generator schließt PR und löscht Branche
Siehe [hier](https://user-images.githubusercontent.com/26322754/120069684-791d1880-c087-11eb-9cb3-8a83c43b0e4d.png)
/SWE-KASCHE/appendix/LKF.md ist nicht in TARGET_PATHS angegeben, wir wollen auch nicht unbedingt einen TOC.

Ursache: 
...?

Fix:
...?

**Comment by ZeroPointMax** [comment]
What in the name of ****

**Comment by nukerxy** [comment]
In #61 habe ich die .md Datei umbenannt.
In #62 habe ich keine .md Datei
In #63 nur nochmal den Namen der .txt geändert.
Ich habe die Logs der Actions "Pull request opened" von Max und von mir verglichen.
Diese sind nicht sehr sprechend - fast alles ist gleich - ich konnte dort nichts finden.

Ergebnis: 
Hier liegt vermutlich ein Konfigurationsfehler in der .yaml des DocToc vor -  Oder er hat unabhängig davon einen Bug.

Zur Erinnerung:
Alle PR haben gemeinsam, dass sie nicht auf main mergen wollen.
Außerdem sind die geänderten Dateien nicht im TARGET_PATH der .yaml angegeben.

sigh

**Comment by ZeroPointMax** [comment]
Wie in #65 zu sehen, liegt es anscheinend nicht an ``TARGET_PATH``

**Comment by ZeroPointMax** [comment]
@nukerxy darf ich vorschlagen, als Workaround erstmal ``git merge`` zu benutzen, damit du wenigstens vorankommst?

**Comment by nukerxy** [comment]
@ZeroPointMax Meinst ohne PR meine Branches auf die von Yannis mergen; Und dann später mit PR auf main?
Ob das gut geht.. haha

**Comment by nukerxy** [comment]
Ich kann die Merge-Konflikte schon kommen sehen 🙈

**Comment by nukerxy** [comment]
@Steve2955 Wenn du mir das Ok gibst, mache ich das so
Für 1-5 hab ich einige, nicht alle, Fragen beantwortet
 heute und morgen geht's weiter

**Comment by Steve2955** [comment]
@nukerxy Go ahead 👍

**Comment by nukerxy** [comment]
commit (https://github.com/importPI19fromDHGE/dhge-pi19-sem4/commit/ecd12567b2302959b2a749d3da11c6e85d3a6b74)
seems to resolve #59.
as seen in #71 #70

**Comment by nukerxy** [comment]
It's back #90

**Comment by ZeroPointMax** [comment]
Och neeee

**Comment by Steve2955** [comment]
@ZeroPointMax  @nukerxy Bei #92 hat's funktioniert 😅

**Comment by Steve2955** [comment]
@nukerxy So wie ich das gesehen habe, war der Test nicht erfolgreich, oder?

**Comment by nukerxy** [comment]
Fehlgeschlagen, ich steig nicht durch

**Comment by Steve2955** [comment]
Lösungsvorschlag: TOC-Action nur laufen lassen, wenn auf `main` germergt wird 😂

**Comment by Steve2955** [comment]
@nukerxy Btw: It work's on my machine #98 😅

**Comment by nukerxy** [comment]
works on my machine #92 und #98 war auch #100

#101 failt wieder

Wir können festhalten: Wenn Yannis die PR öffnet, weil die Action irgendwie mit ihm zu tun hat, ist alles i.O.
Sonst gibt's Probleme.

**Comment by Steve2955** [comment]
#101 hatte keinen Merge mit dem Upstream, daher die alte Config (siehe [hier](https://github.com/importPI19fromDHGE/dhge-pi19-sem4/blob/3c48b40140b13be55640205b26cdf03f5f27bd62/.github/workflows/toc.yml))

**Comment by Steve2955** [comment]
> Wenn Yannis die PR öffnet, weil die Action irgendwie mit ihm zu tun hat, ist alles i.O.
> Sonst gibt's Probleme.

Die Action hat übrigens nur was mit mir zu tun, weil sie einen Key von mir nutzt, um Commits pushen zu können
