### ISSUE TITLE
Fehlendes Bild

### ISSUE THREAD

**Issue by RvNovae** [importPI19fromDHGE/dhge-pi19-sem4#75]
Hier ist anscheinend ein Bild verloren gegangen:
https://github.com/importPI19fromDHGE/dhge-pi19-sem4/blob/main/ASM-GUENTHER/appendix/praktikum.md#externe-interrupts

**Comment by ZeroPointMax** [comment]
aaahhh ich dachte, ich hätte es korrigiert
