### ISSUE TITLE
Richtiges gitignore

### ISSUE THREAD

**Issue by nukerxy** [importPI19fromDHGE/dhge-pi19-sem4#80]
Siehe [commit](https://github.com/importPI19fromDHGE/dhge-pi19-sem4/commit/34ab0208291fd94c7f093072d26b0b26df2743b6)
So geht das ja nicht...
Möchte gern .asm-Files in diesem Ordner nicht ignorieren
Branch wählen, Pfad anschauen. Habs probiert, nach Recherche... Github Desktop wollte es nicht annehmen, es sei denn ich habe es so gemacht.
@Steve2955 @ZeroPointMax

**Comment by Steve2955** [comment]
Hab's mir jetzt nicht genau angesehen, aber `.asm` hört sich nach was an, dass eigentlich im `extra` Ordner landen sollte. Wie es der `popcnt` bei Günther direkt in den Modul-Ordner geschafft hat, weiß ich auch nicht, aber das stört mich schon länger. 😂 

Vgl. [dhge-pi19-sem3/issues/89](https://github.com/importPI19fromDHGE/dhge-pi19-sem3/issues/89#issuecomment-753790457)

Unabhängig davon sollten wir in der `.gitignore` den `extra`-Ordner wahrscheinlich für beliebige Dateiformate freigeben 🤔

**Comment by nukerxy** [comment]
popcnt geht auf meine Kappe 😁 
ok, kommt in extras, dann ist das ja klar.
[commit1] (https://github.com/importPI19fromDHGE/dhge-pi19-sem4/commit/fb1d170337357e0615df9d389689c4575c9ba72e)
[commit2] (https://github.com/importPI19fromDHGE/dhge-pi19-sem4/commit/46758d9ad6907089c37f8f81ed988593118b27ef)
jetzt hats auch geklappt. 🤷
